application: mktzcrew
version: 5
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: css
  
- url: /script
  static_dir: script
  
- url: /Authentication/.*
  script: authentication.py
  secure: always

- url: /Data/.*
  script: Data.py
  secure: always
  
- url: /.*
  script: index.py
  secure: always